### ISSUE TITLE
Release 1.0.0 with modis 2.x support

### ISSUE THREAD

**Issue by aried3r** [rpush/rpush-redis#3]
Hey @Tonkpils, do you think we can get a CHANGELOG and maybe migration instructions going for this one?

@ileitch gave me publishing permission for this gem, so I can roll a new release anytime :)

**Comment by Tonkpils** [comment]
Hey! sure, I'll get to that possibly tonight or over the weekend but I'd be happy to add that on

**Comment by anolson** [comment]
Hi! 👋 

Is there a chance that you could cut a `1.0.0` release sometime soon.  It looks like the `gemspec` has been updated on master with modis 2.x support.

**Comment by Tonkpils** [comment]
Hey all, sorry for the delay, it's been fairly busy. This is on my radar to complete by early next week but feel free to tackle it on if anyone wants to make a PR, I have to gather a bit more context around the gem as I don't use it day-to-day anymore 😞

**Comment by Tonkpils** [comment]
@aried3r I've gone ahead and published a CHANGELOG for modis 2.x+ https://github.com/ileitch/modis/blob/master/CHANGELOG.md.

As far as the upgrade path, the only thing that I think we'd need to specify or account for is any persisted records in Redis that may have been serialized with YAML.

Prior to Modis 2, you'd get a warning when (de)serializing with YAML and you'd have to re-run the save command for specific records with `save(yaml_sucks: true)`. YAML support was removed in Modis 2.

**Comment by aried3r** [comment]
Hey, sorry. I'll try to get these out this month. Been too busy. :\

I saw that modis fails to build on `master`, could you check that maybe?

**Comment by aried3r** [comment]
Also, does this need to be a gem at all? It's literally 7 lines of code that don't do anything but cause work since it has to be maintained (case in point, this issue).

https://github.com/rpush/rpush-redis/blob/master/lib/rpush/redis.rb

**Comment by garettarrowood** [comment]
+1 to releasing a version that supports Ruby 2.4.x .  @Tonkpils - The master failures on `modis` were just `rubocop` offenses. These are resolved here - https://github.com/ileitch/modis/pull/12 .

**Comment by Tonkpils** [comment]
@aried3r I've merged the build fixes into `modis` master. As far as this gem being needed, I believe `rpush` required this in order to use the redis functionality but I can't be sure since it's been a while since I used `rpush` and `rpush-redis`.

**Comment by aried3r** [comment]
https://rubygems.org/gems/rpush-redis/versions/1.0.1

Sorry for the wait everyone, I just released 1.0.1 with all the changes.

I still think we should just have that in the Rpush README with all of the necessary code instead of this gem here, although it's nice that including this also comes with all the dependencies, which is only `modis`. But oh well.

**Comment by Tonkpils** [comment]
I think the idea may be that you'll only require modis when you're using rpush with redis. Otherwise it'd be an unnecessary dependency. Thanks for releasing the new version!
